// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movieCollection.Models;

namespace movieCollection.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20220127020012_v2")]
    partial class v2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("movieCollection.Models.Movie", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("movieID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            movieID = 1,
                            category = "Action/Adventure",
                            director = "Tim Burton",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman",
                            year = 1989
                        },
                        new
                        {
                            movieID = 2,
                            category = "Action/Adventure",
                            director = "Joel Schumacher",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman & Robin",
                            year = 1997
                        },
                        new
                        {
                            movieID = 3,
                            category = "Action/Adventure",
                            director = "Christopher Nolan",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman Begins",
                            year = 2005
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
