// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movieCollection.Models;

namespace movieCollection.Migrations
{
    [DbContext(typeof(MoviesContext))]
    partial class MoviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("movieCollection.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("categoryID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            categoryID = 1,
                            categoryName = "Action/Adventure"
                        },
                        new
                        {
                            categoryID = 2,
                            categoryName = "Comedy"
                        },
                        new
                        {
                            categoryID = 3,
                            categoryName = "Drama"
                        });
                });

            modelBuilder.Entity("movieCollection.Models.Movie", b =>
                {
                    b.Property<int>("movieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("categoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("movieID");

                    b.HasIndex("categoryID");

                    b.ToTable("movies");

                    b.HasData(
                        new
                        {
                            movieID = 1,
                            categoryID = 1,
                            director = "Tim Burton",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman",
                            year = 1989
                        },
                        new
                        {
                            movieID = 2,
                            categoryID = 1,
                            director = "Joel Schumacher",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman & Robin",
                            year = 1997
                        },
                        new
                        {
                            movieID = 3,
                            categoryID = 1,
                            director = "Christopher Nolan",
                            edited = false,
                            lentTo = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Batman Begins",
                            year = 2005
                        });
                });

            modelBuilder.Entity("movieCollection.Models.Movie", b =>
                {
                    b.HasOne("movieCollection.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
